### PR TITLE
fix: correct incompatibilities with IC-2024.1 (#719)

### LINKED ISSUE #719: fix IC-2024.1 compatibility problems
depends on https://github.com/redhat-developer/intellij-common/issues/207

See https://plugins.jetbrains.com/plugin/15921-kubernetes-by-red-hat/edit/versions/stable/463954

image

### PR DESCRIPTION
**Pull request by adietish**
fixes #719

### CODE REVIEW

**Comment by adietish** [comment]
@sbouchet: please review

File: src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/util/ResourceUtils.kt [hunk 1]
```diff
@@ -10,6 +10,7 @@
  ******************************************************************************/
 package com.redhat.devtools.intellij.kubernetes.model.util
 
+import com.intellij.openapi.diagnostic.Logger
 import com.intellij.openapi.diagnostic.logger
```
Comment (sbouchet) [inline src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/util/ResourceUtils.kt:14]: duplicate import ?

**Review by sbouchet — APPROVED** [review]
LGTM
