### PR TITLE
fix: create lazy OpenShift context to avoid check timeouts (#865)

### LINKED ISSUE #865: Nothing happens if I try to set a non-responsive cluster as current cluster
related to 
* #862 
* #869

---
**Steps:**
1. ASSERT: have a cluster that's shut down (ex. have kind cluster defined in kubeconfig, but it's not running)
2. EXEC: in resource tree: right click on the entry for the non-responsive cluster and pick "Set as current cluster"

**Result:**
Nothing happens. In the status bar you see a running operation "Setting kind as current cluster". This operation can easily be running for several minutes.
Even worse is that the IDE cannot be closed gracefully when this operation is running. You have to forcefully kill it.

---

**Steps 2:**
1. ASSERT: have a cluster that's shut down (ex. have kind cluster defined in kubeconfig, but it's not running)
2. EXEC: start up the IDE, open the Kubernetes tool window. Wait for the contexts to be listed.

**Result:**
It takes several seconds (~20s in my case) until the contexts are listed

---
I suspect this to have been introduced with the switch to the new kubernetes-client 7.0.0

### PR DESCRIPTION
**Pull request by adietish**
fixes #865

### CODE REVIEW

File: src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/client/ClientAdapter.kt [hunk 1]
```diff
@@ -76,12 +96,14 @@ abstract class ClientAdapter<C : KubernetesClient>(private val fabric8Client: C)
...
-                KubeClientAdapter(kubeClient)
-            }
+            /**
+             *  Always create kubernetes client.
+             *  Upgrade existing client to OpenShift only async bcs checking if cluster is OpenShift is costly
+             *  and may timeout if cluster is not reachable.
+             *  @see [issue 865](https://github.com/redhat-developer/intellij-kubernetes/issues/865)
+             *  @see ClientAdapter.toOpenShift
+             **/
+            return KubeClientAdapter(kubeClient)
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/client/ClientAdapter.kt:106]: this is the core of the fix: dont check if the cluster is OpenShift and create a Kubernetes- or OpenShift context. This check is costly and may timeout if the cluster is not reachable.
Create a Kubernetes context that async tries to upgrade to an OpenShift context instead.

File: src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/context/IActiveContext.kt [hunk 2]
```diff
@@ -23,30 +24,29 @@ import io.fabric8.kubernetes.api.model.apiextensions.v1.CustomResourceDefinition
...
-                    client as OSClientAdapter
-                )
-            } else {
-                KubernetesContext(
-                    currentContext,
-                    observable,
-                    client as KubeClientAdapter
-                )
-            }
+            return LazyOpenShiftContext(currentContext, modelChange, client as KubeClientAdapter)
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/context/IActiveContext.kt:39]: this is the core of the fix: dont check if the cluster is OpenShift and create a Kubernetes- or OpenShift context. This check is costly and may timeout if the cluster is not reachable.
Create a Kubernetes context that async tries to upgrade to an OpenShift context instead.

File: src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/client/ClientAdapter.kt [hunk 3]
```diff
@@ -52,17 +56,33 @@ open class KubeClientAdapter(client: KubernetesClient) :
...
 }
 
 abstract class ClientAdapter<C : KubernetesClient>(private val fabric8Client: C) {
 
     companion object Factory {
 
+        const val TIMEOUT_CONNECTION = 5000
+        const val TIMEOUT_REQUEST = 5000
+        const val LIMIT_RECONNECT = 2
+
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/client/ClientAdapter.kt:74]: This is a sidenote of the fix: impose timeouts for connecting, requesting and reconnecting.

File: src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/client/ClientAdapter.kt [hunk 4]
```diff
@@ -52,17 +56,33 @@ open class KubeClientAdapter(client: KubernetesClient) :
...
             namespace: String? = null,
             context: String? = null,
             clientBuilder: KubernetesClientBuilder? = null,
-            createConfig: (context: String?) -> Config = { context -> Config.autoConfigure(context) },
+            createConfig: (context: String?) -> Config = { context ->
+                val config = Config.autoConfigure(context)
+                config.connectionTimeout = TIMEOUT_CONNECTION
+                config.requestTimeout = TIMEOUT_REQUEST
+                config.watchReconnectLimit = LIMIT_RECONNECT
+                config
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/client/ClientAdapter.kt:84]: This is an aspect of the fix: impose timeouts for connecting, requesting and reconnecting.

File: src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/context/LazyOpenShiftContext.kt [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+    }
+
+    override fun getDashboardUrl(): String? {
+        lock.read {
+            return delegate.getDashboardUrl()
+        }
+    }
+
+    private fun createOpenShiftDelegate() {
+        if (client.canAdaptToOpenShift()) {
```
Comment (adietish) [inline src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/context/LazyOpenShiftContext.kt:100]: this is the core fix: a context that starts as a Kubernetes context and async tries to create and use an OpenShift context.

File: src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/context/LazyOpenShiftContext.kt [hunk 6]
```diff
@@ -0,0 +1,112 @@
+/*******************************************************************************
+ * Copyright (c) 2020 Red Hat, Inc.
```
Comment (sbouchet) [inline src/main/kotlin/com/redhat/devtools/intellij/kubernetes/model/context/LazyOpenShiftContext.kt:2]: we're in 2025 :D

**Comment by adietish** [comment]
@sbouchet please re-review/test

**Comment by adietish** [comment]
@sbouchet: handing this to @msivasubramaniaan to unload you so that you can please review #642

**Review by msivasubramaniaan — APPROVED** [review]
I have tested as per the steps mentioned on the PR and it is working fine. LGTM

**Comment by adietish** [comment]
@msivasubramaniaan thx for testing!
