### PR TITLE
replaced 'Delete' icon deprecated in IC-2020.1 (#172)

### LINKED ISSUE #172: PluginException: Icon cannot be found in 'AllIcons.Modules.DeleteContentFolder'
Reported via jetbrains plugins listing at https://plugins.jetbrains.com/plugin/15921-kubernetes-by-red-hat

```
com.intellij.diagnostic.PluginException: Icon cannot be found in 'AllIcons.Modules.DeleteContentFolder', action 'class com.redhat.devtools.intellij.kubernetes.actions.DeleteResourceAction' [Plugin: com.redhat.devtools.intellij.kubernetes] at 
com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:390) at 
com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:385) at 
com.intellij.openapi.actionSystem.impl.ActionManagerImpl.setIconFromClass(ActionManagerImpl.java:302) at 
com.intellij.openapi.actionSystem.impl.ActionManagerImpl.updateIconFromStub(ActionManagerImpl.java:267) at 
com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:227) at 
com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:570) at 
com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1621) at 
com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:15) at 
com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84) at 
com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178) at 
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658) at 
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610) at 
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65) at 
com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165) at 
com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74) at 
com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216) at 
com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27) at 
com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195) at 
com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208) at 
com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184) at 
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at 
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at 
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668) at 
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665) at 
java.base/java.security.AccessController.doPrivileged(Native Method) at 
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665) at 
java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by adietish**
fixes #172

### CODE REVIEW

**Comment by adietish** [comment]
The icon that fails to be loaded is referenced by an action in plugin.xml
```
            <action class="com.redhat.devtools.intellij.kubernetes.actions.DeleteResourceAction"
                    id="com.redhat.devtools.intellij.kubernetes.actions.DeleteResourceAction"
                    text="Delete"
                    icon="AllIcons.Actions.Close"/>
```
I thus added tests that assert the existence of these icons.

File: src/test/kotlin/com/redhat/devtools/intellij/kubernetes/tree/PluginXmlIconsTest.kt [hunk 1]
```diff
@@ -0,0 +1,47 @@
+/*******************************************************************************
+ * Copyright (c) 2020 Red Hat, Inc.
```
Comment (jeffmaury) [inline src/test/kotlin/com/redhat/devtools/intellij/kubernetes/tree/PluginXmlIconsTest.kt:2]: Should be 2021 ?

**Review by jeffmaury — APPROVED** [review]
LGTM
